os:
  - linux
language: python
branches:
  only:
  - release
addons:
  apt:
    packages:
    - unzip
before_install:
  - pip install z3-solver
  - pip3 install z3-solver
install:
  - python setup.py install
  - python3 setup.py install
  - pip install tox
script:
  - tox
env:
  - TOXENV=py27
  - TOXENV=py27-full
  - TOXENV=py3
  - TOXENV=py3-full
