os:
  - linux
language: python
branches:
  only:
  - release
addons:
  apt:
    packages:
    - unzip
    - python3
before_install:
  - wget -q -O /tmp/z3.zip https://github.com/Z3Prover/z3/archive/z3-4.5.0.zip
  - mkdir z3
  - unzip -q -d z3 -j /tmp/z3.zip
  - cd z3
  - python scripts/mk_make.py
  - cd build; make install
  - python3 scripts/mk_make.py
  - cd build; make install
install:
  - python setup.py install
  - python3 setup.py install
  - pip install tox
script:
  - tox
env:
  - TOXENV=py27
  - TOXENV=py27-full
  - TOXENV=py3
  - TOXENV=py3-full
